##################### Style ##################################

Style/AlignHash:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table
  EnforcedLastArgumentHashStyle: ignore_implicit

Style/AsciiComments:
  Enabled: false

Style/BlockDelimiters:
  EnforcedStyle: semantic

Style/Documentation:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/MultilineOperationIndentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/TrailingComma:
  Enabled: false


##################### Metrics ##################################

Metrics/AbcSize:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false
